/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.InventoryBE;
import backend.ProductBE;
import backend.PurchaseBE;
import backend.SupplierBE;
import backend.UserAuth;
import entities.Inventory;
import entities.Product;
import entities.Supplier;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ajai Lee
 */
public class AddInventory extends javax.swing.JFrame {

    static List<Product> productList = null;
    static List<Inventory> inventoryList = new ArrayList<Inventory>();
    static double total = 0;

    static AddInventory instance;

    static void buildUI() {
        if (instance == null) {
            instance = new AddInventory();
        }
        instance.setVisible(true);
        instance.requestFocus();
    }

    /**
     * Creates new form ViewSupplier
     */
    private AddInventory() {
        initComponents();
        loadSupplierAndProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_purchaseId = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_productId = new javax.swing.JTextField();
        txt_purchaseprice = new javax.swing.JTextField();
        txt_saleprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_margin = new javax.swing.JTextField();
        txt_supplier = new javax.swing.JComboBox<>();
        txt_product = new javax.swing.JComboBox<>();
        cmd_deleteOrReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_qty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_gst = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lab_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Purchase Id");

        jLabel2.setText("Supplier");

        jLabel3.setText("Purchase Date");

        jDateChooser1.setDateFormatString("d-MMM-y");

        jLabel4.setText("Product ID");

        jLabel5.setText("Product Name");

        jLabel6.setText("Buying Price");

        jLabel7.setText("Selling Price");

        txt_productId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_productIdKeyPressed(evt);
            }
        });

        jLabel8.setText("Margine");

        txt_supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txt_product.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_productItemStateChanged(evt);
            }
        });

        cmd_deleteOrReset.setText("Reset");
        cmd_deleteOrReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_deleteOrResetMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Product ID", "Product Name", "Buying  Price", "Selling Price", "Margin", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Qty");

        jButton2.setText("CANCEL");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("SAVE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("ADD");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        txt_gst.setEditable(false);

        jLabel10.setText("GST %");

        lab_total.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_purchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_productId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(txt_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_product, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_purchaseprice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_saleprice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_margin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_gst, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmd_deleteOrReset))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lab_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_purchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaseprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_saleprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_margin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_deleteOrReset)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(txt_gst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lab_total, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_productItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_productItemStateChanged
        // TODO add your handling code here:
        int index = txt_product.getSelectedIndex();
        System.out.println(index);
        if (index == -1) {

        } else {
            Product p = productList.get(index);
            setDetails(p);
        }

    }//GEN-LAST:event_txt_productItemStateChanged

    private void txt_productIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productIdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_product.setSelectedItem(getName(txt_productId.getText()));
        }
    }//GEN-LAST:event_txt_productIdKeyPressed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        addToTable();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            cmd_deleteOrReset.setText("Delete Row");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmd_deleteOrResetMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (cmd_deleteOrReset.getText().equals("Delete Row")) {

            // TODO add your handling code here:
//            logger.debug("cmd_DeletemouseClicked:::AddInventory2:::begin");
//            logger.info("selected row in cmd_deleteMouseClicked::::AddInventory2" + jTable1.getSelectedRow());
            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
            int row_count = jTable1.getSelectedRow();
            double subTotal = (double) jTable1.getValueAt(row_count, 7);
            total = total - subTotal;
            lab_total.setText(String.valueOf((total)));
            System.out.println(inventoryList.get(row_count));
            inventoryList.remove(row_count);
            System.out.println(inventoryList.toString());
            tb.removeRow(row_count);
            for (int index = row_count; index < tb.getRowCount(); index++) {
                tb.setValueAt(index + 1, index, 0);
            }
            cmd_deleteOrReset.setText("Reset");
        } else {
            reset();
            //sample recording with obs 
        }
    }

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (txt_purchaseId.getText().isBlank() || txt_supplier.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Check The Supplier and Purchase Id");
            return;
        } else if (jTable1.getRowCount() == -1 || inventoryList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cant Add An Empty List");
            return;
        }
        try {
            String purchaseId =txt_purchaseId.getText();
            String supplierName =txt_supplier.getSelectedItem().toString();
            Date date = jDateChooser1.getDate();
            String addedBy = UserAuth.user.getId().toString();
            Date addTime =  new Date();
            boolean success = InventoryBE.add(inventoryList,purchaseId,supplierName,date,addedBy,addTime);
            
            if (success) {
                clearTable();
                JOptionPane.showMessageDialog(this, "Products Successfully Added");
            } else {
                JOptionPane.showMessageDialog(this, "Cant Add Products");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Sure? Do You want to Cancel?No Data will be saved", "Cancel",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            clearTable();
            txt_supplier.setSelectedIndex(0);
            txt_purchaseId.setText("");

        } else if (result == JOptionPane.NO_OPTION) {
            return;
        }

    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_deleteOrReset;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lab_total;
    private javax.swing.JTextField txt_gst;
    private javax.swing.JTextField txt_margin;
    private javax.swing.JComboBox<String> txt_product;
    private javax.swing.JTextField txt_productId;
    private javax.swing.JTextField txt_purchaseId;
    private javax.swing.JTextField txt_purchaseprice;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_saleprice;
    private javax.swing.JComboBox<String> txt_supplier;
    // End of variables declaration//GEN-END:variables
  private void loadSupplierAndProduct() {
        List<Supplier> supplierList = SupplierBE.getAllSupplier();
        productList = ProductBE.getAllProduct();

        txt_supplier.removeAllItems();
        for (Supplier c : supplierList) {
            txt_supplier.addItem(c.getName());

        }

        txt_product.removeAllItems();
        for (entities.Product b : productList) {
            txt_product.addItem(b.getName());
        }
//        for(int i=100;i<4000;i++){
//            txt_product.addItem(String.valueOf(i));
//        }
        AutoCompleteDecorator.decorate(txt_supplier);
        AutoCompleteDecorator.decorate(txt_product);

    }

    private void setDetails(Product p) {
        txt_productId.setText(p.getId());
        txt_gst.setText(String.valueOf(p.getGst()));

    }

    private String getName(String id) {
        System.out.println("typed Index" + id);
        for (Product p : productList) {
            System.out.println(p.getId());
            if (p.getId().equals(id)) {
                return p.getName();
            }
        }
        return "No Product Found";
    }

    private Product getProduct(String id) {
        System.out.println("typed Index" + id);
        for (Product p : productList) {
            System.out.println(p.getId());
            if (p.getId().equals(id)) {
                return p;
            }
        }
        return null;
    }

    private void addToTable() {
        try {
            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();

            if (txt_margin.getText().isBlank()) {
                //double p,double c,double d,int g
                double s = Double.valueOf(txt_saleprice.getText());
                double p = Double.valueOf(txt_purchaseprice.getText());

                double margin = calMargin(s, p);
                txt_margin.setText(String.valueOf(margin));

            } else {
                double c = Double.valueOf(txt_purchaseprice.getText());
                double m = Double.valueOf(txt_margin.getText());
                double price = calPrice(c, m);
                txt_saleprice.setText(String.valueOf(price));

            }
            double subTotal = Double.valueOf(txt_purchaseprice.getText()) * Double.valueOf(txt_qty.getText());
            Object[] rowData = {jTable1.getRowCount() + 1, txt_productId.getText(), txt_product.getSelectedItem(), txt_purchaseprice.getText(), txt_saleprice.getText(), txt_margin.getText(), txt_qty.getText(), subTotal};
            total = total + subTotal;
            lab_total.setText(String.valueOf(total));
            tb.addRow(rowData);

            Inventory i = new Inventory(getProduct(txt_productId.getText()), Double.valueOf(txt_purchaseprice.getText()), Double.valueOf(txt_saleprice.getText()), Double.valueOf(txt_margin.getText()), Integer.valueOf(txt_qty.getText()));
            inventoryList.add(i);
            System.out.println(inventoryList.toString());

            reset();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }

    private double calPrice(double c, double m) {
        double Price = c / (1 - m);
        String br = String.format("%.2f", Price);
        return Double.valueOf(br);
    }

    private double calMargin(double s, double p) {
        System.out.println("callled calMargin");

        double Margin = (s - p) / (s * 100);
        String br = String.format("%.2f", Margin * 100);

        return Double.valueOf(br);
    }

    private void clearTable() {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        tb.setRowCount(0);
        inventoryList.clear();

    }

    private void reset() {
        //  Date x = jDateChooser1.getDate();
        txt_productId.setText("");
        txt_qty.setText("");
        txt_purchaseprice.setText("");
        txt_margin.setText("");
        txt_saleprice.setText("");

    }
}
