/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import entities.Supplier;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.InputValidate;


/**
 *
 * @author Ajai Lee
 */
public class EditSupplier extends javax.swing.JFrame {

    static EditSupplier instance;

    static void buildUI() {
        if (instance == null) {
            instance = new EditSupplier();
        }
        instance.setVisible(true);
        instance.requestFocus();
    }

    /**
     * Creates new form AddSupplier
     */
    private EditSupplier() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_phoneNo = new javax.swing.JTextField();
        txt_gstNo = new javax.swing.JTextField();
        txt_accountNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_extra = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        cmd_save = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Phone Number");

        jLabel3.setText("Address");

        jLabel4.setText("Extra");

        jLabel5.setText("Account Number");

        jLabel6.setText("GST NO");

        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });

        txt_phoneNo.setEditable(false);
        txt_phoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phoneNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_phoneNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneNoKeyTyped(evt);
            }
        });

        txt_gstNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gstNoActionPerformed(evt);
            }
        });
        txt_gstNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_gstNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_gstNoKeyTyped(evt);
            }
        });

        txt_accountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_accountNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_accountNoKeyTyped(evt);
            }
        });

        txt_extra.setColumns(20);
        txt_extra.setRows(5);
        jScrollPane1.setViewportView(txt_extra);

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane2.setViewportView(txt_address);

        cmd_save.setText("Update");
        cmd_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_saveMouseClicked(evt);
            }
        });

        cmd_clear.setText("Clear");
        cmd_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_clearMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("jLabel7");
        jLabel7.setVisible(false);

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("jLabel7");
        jLabel8.setVisible(false);

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("jLabel7");
        jLabel9.setVisible(false);

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("jLabel7");
        jLabel10.setVisible(false);
        jLabel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel10KeyTyped(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("jLabel7");
        jLabel11.setVisible(false);

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("jLabel7");
        jLabel12.setVisible(false);

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel13.setText("Phone Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel7)
                .addGap(636, 636, 636)
                .addComponent(jLabel8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txt_accountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel9)
                .addGap(638, 638, 638)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel11)
                .addGap(638, 638, 638)
                .addComponent(jLabel12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(524, 524, 524)
                .addComponent(cmd_save)
                .addGap(101, 101, 101)
                .addComponent(cmd_clear))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txt_name))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_gstNo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel13))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gstNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_accountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_save)
                    .addComponent(cmd_clear)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_gstNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gstNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gstNoActionPerformed

    private void cmd_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_saveMouseClicked
        // TODO add your handling code here:
        String name = txt_name.getText();
        String phoneNumber = txt_phoneNo.getText();
        String accountNumber = txt_accountNo.getText();
        String gstNo = txt_gstNo.getText();
        String address = txt_address.getText();
        String extra = txt_extra.getText();
       if( backend.Supplier.updateSupplier(name, phoneNumber, gstNo, accountNumber, address, extra)){
           JOptionPane.showMessageDialog(this, "Supplier Updated Successfully");
        clear();
       }else{
            JOptionPane.showMessageDialog(this, "SomeThing Went Wrong");
       }
        
    }//GEN-LAST:event_cmd_saveMouseClicked

    private void cmd_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_clearMouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cmd_clearMouseClicked

    private void txt_gstNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gstNoKeyTyped
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_txt_gstNoKeyTyped

    private void txt_phoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneNoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_phoneNoKeyPressed

    private void txt_phoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneNoKeyTyped
        // TODO add your handling code here:
          
       
         
    }//GEN-LAST:event_txt_phoneNoKeyTyped

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_nameKeyTyped

    private void jLabel10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel10KeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabel10KeyTyped

    private void txt_accountNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_accountNoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_accountNoKeyTyped

    private void txt_phoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneNoKeyReleased
        // TODO add your handling code here:
         jLabel9.setText("Invalid Phone Number");
          jLabel9.setVisible(txt_phoneNo.getText().length()>10||txt_phoneNo.getText().length()<10);
     //   jLabel9.setVisible(InputValidate.validatePhoneNumber(txt_phoneNo.getText()));
    }//GEN-LAST:event_txt_phoneNoKeyReleased

    private void txt_accountNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_accountNoKeyReleased
        // TODO add your handling code here: 
        jLabel10.setText("Invalid Account Number");
        jLabel10.setVisible(!InputValidate.validateAccountNo(txt_accountNo.getText()));
    }//GEN-LAST:event_txt_accountNoKeyReleased

    private void txt_gstNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gstNoKeyReleased
        // TODO add your handling code here:
        jLabel8.setText("Invalid GST");
        jLabel8.setVisible(!InputValidate.validateGst(txt_gstNo.getText()));
    }//GEN-LAST:event_txt_gstNoKeyReleased

    private void txt_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyReleased
        // TODO add your handling code here:
        jLabel7.setText("Invalid Name");
        jLabel7.setVisible(!InputValidate.validateName(txt_name.getText()));
    }//GEN-LAST:event_txt_nameKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        search(txt_search.getText());
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_accountNo;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextArea txt_extra;
    private javax.swing.JTextField txt_gstNo;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phoneNo;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txt_name.setText("");
        txt_phoneNo.setText("");
        txt_accountNo.setText("");
        txt_gstNo.setText("");
        txt_address.setText("");
        txt_extra.setText("");//To change body of generated methods, choose Tools | Templates.
    }

    private void search(String text) {
    Supplier s= backend.Supplier.searchSupplier(text);
    if(s==null){
        JOptionPane.showMessageDialog(this, "No Supplier Found With This Number");
    }
    else{
        txt_name.setText(s.getName());
        txt_accountNo.setText(s.getAccountNo().toString());
        txt_gstNo.setText(s.getGstNo());
        txt_phoneNo.setText(s.getPhoneNo().toString());
        txt_address.setText(s.getAddress());
        txt_extra.setText(s.getExtra());
        
    }
    }
}
